apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany 
  volumeName: pv-mongo
  resources:
    requests:
      storage: 1Gi
