service:  
 name: "logging-pod"
 clusterIP: 10.102.2.101
 type: LoadBalancer
 ports:
  internal: 15456
  external: 5101
  protocol: TCP

deployment:
 application:
  name: "logging-pod"
  containers:
   loggingContainer:
    port: 15456
    environment:
     ApplicationName: "Logging Service Test Environment"
     Configuration_Authorization_Credential_Email: "Services.Api.Logging@service.service"
     Configuration_Authorization_Credential_Password: "1234"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_RequestResponseLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RequestResponseLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Host: "https://192.168.1.177:9200"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_UserName: "elastic"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Password: "L1tO811luDVj-oTTbEHp"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Index: "log-microservice-request-response"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_ExceptionLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_ExceptionLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_Host: "https://192.168.1.177:9200"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_UserName: "elastic"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_Password: "L1tO811luDVj-oTTbEHp"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_Index: "log-microservice-exception"
     Configuration_WebSockets_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Socket_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Caching_Redis_Server: "svc-redis.default.svc.cluster.local"     
     Persistence_Databases_Microservice_Logs_DB_ConnectionString: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
  image:
   imagePullPolicy: Always
   name: "serkancamur/logging"
   tag: "latest"
