apiVersion: v1
kind: Service
metadata:
  name: accounting-service
spec:
  selector:
    app: accounting-pod
  ports:
  - port: 5103
    targetPort: 30775
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.103