apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
spec:
  selector:
    matchLabels:
      app: authorization-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: authorization-pod
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: authorization-container
          image: serkancamur/authorization:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 15455
          env:
            - name: ApplicationName
              value: "Authorization Service"
            - name: Configuration_Localization_TranslationDbConnnectionString
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Localization_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Host
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_Logging_RequestResponseLogging_RabbitConfiguration_UserName
              value: "rabbituser"
            - name: Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Password
              value: "rabbitpassword"
            - name: Configuration_Logging_RequestResponseLogging_DataBaseConfiguration_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_RequestResponseLogging_MongoConfiguration_ConnectionString
              value: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Host
              value: "https://192.168.1.177:9200"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_UserName
              value: "elastic"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Password
              value: "L1tO811luDVj-oTTbEHp"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Index
              value: "log-microservice-request-response"
            - name: Configuration_Logging_ExceptionLogging_RabbitConfiguration_Host
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_Logging_ExceptionLogging_RabbitConfiguration_UserName
              value: "rabbituser"
            - name: Configuration_Logging_ExceptionLogging_RabbitConfiguration_Password
              value: "rabbitpassword"
            - name: Configuration_Logging_ExceptionLogging_DataBaseConfiguration_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_ExceptionLogging_MongoConfiguration_ConnectionString
              value: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_Host
              value: "https://192.168.1.177:9200"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_UserName
              value: "elastic"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_Password
              value: "L1tO811luDVj-oTTbEHp"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_Index
              value: "log-microservice-exception"
            - name: Configuration_RabbitQueues_Host_DefaultHost
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_RabbitQueues_Host_DefaultUserName
              value: "rabbituser"
            - name: Configuration_RabbitQueues_Host_DefaultPassword
              value: "rabbitpassword"
            - name: Configuration_WebSockets_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Socket_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Caching_Redis_Server
              value: "svc-redis.default.svc.cluster.local"
            - name: Persistence_Databases_Microservice_Security_DB_ConnectionString
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Security_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
          volumeMounts:
            - mountPath: "mnt/data"
              name: volume