apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage-pod
  ports:
  - port: 5111
    targetPort: 58984
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.111