apiVersion: v1
kind: Service
metadata:
  name: aa-service
spec:
  selector:
    app: aa-pod
  ports:
  - port: 5104
    targetPort: 34308
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.104