apiVersion: v1
kind: Service
metadata:
  name: hr-service
spec:
  selector:
    app: hr-pod
  ports:
  - port: 5102
    targetPort: 26920
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.102