service:  
 name: "presentationuiwebidentity-pod"
 clusterIP: 10.102.2.98
 type: NodePort
 ports:
  internal: 31636
  external: 5098
  protocol: TCP
  nodeport: 31098

deployment:
 application:
  name: "presentationuiwebidentity-pod"
  containers:
   presentationuiwebidentityContainer:
    port: 26920
    environment:
     ApplicationName: "Presentation Web UI Identity"
     Configuration_Authorization_Credential_Email: "Presentation.UI.Web.Identity@ui.service"
     Configuration_Authorization_Credential_Password: "1234"
     Configuration_Localization_TranslationDbConnnectionString: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Localization_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_RequestResponseLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RequestResponseLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_RuntimeLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_RuntimeLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_RuntimeLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_RuntimeLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RuntimeLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_ExceptionLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_ExceptionLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_RabbitQueues_Host_DefaultHost: "rabbitmq3.default.svc.cluster.local"
     Configuration_RabbitQueues_Host_DefaultUserName: "rabbituser"
     Configuration_RabbitQueues_Host_DefaultPassword: "rabbitpassword"
     Configuration_WebSockets_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Socket_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Caching_Redis_Server: "svc-redis.default.svc.cluster.local"
  image:
   imagePullPolicy: "Always"
   name: "serkancamur/presentationuiwebidentity"
   tag: "latest"