apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: finance-pod
  ports:
  - port: 5107
    targetPort: 32355
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.107