apiVersion: v1
kind: Service
metadata:
  name: authorization-service
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: {{ .Values.service.ports.external }}
    targetPort: {{ .Values.service.ports.internal }}
    protocol: {{ .Values.service.ports.protocol }}
    nodePort: {{ .Values.service.ports.nodePort }}
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}