service:  
 name: "aa-pod"
 clusterIP: 10.102.2.104
 type: LoadBalancer
 ports:
  internal: 34308
  external: 5104
  protocol: TCP

deployment:
 application:
  name: "aa-pod"
  containers:
   aaContainer:
    port: 34308
    environment:
     ApplicationName: "AA Service Test Environment"
     Configuration_Authorization_Credential_Email: "Services.Api.Business.Departments.aa@service.service"
     Configuration_Authorization_Credential_Password: "1234"
     Configuration_Localization_TranslationDbConnnectionString: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Localization_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_RequestResponseLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RequestResponseLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Host: "https://localhost:9200"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_UserName: "elastic"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Password: "zrZhe7mrQBwVWKnxYQAS"
     Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Index: "log-microservice-request-response"
     Configuration_Logging_RuntimeLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_RuntimeLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_RuntimeLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_RuntimeLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_RuntimeLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_RuntimeLogging_ElasticConfiguration_Host: "https://localhost:9200"
     Configuration_Logging_RuntimeLogging_ElasticConfiguration_UserName: "elastic"
     Configuration_Logging_RuntimeLogging_ElasticConfiguration_Password: "zrZhe7mrQBwVWKnxYQAS"
     Configuration_Logging_RuntimeLogging_ElasticConfiguration_Index: "log-microservice-runtime"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_Host: "rabbitmq3.default.svc.cluster.local"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_UserName: "rabbituser"
     Configuration_Logging_ExceptionLogging_RabbitConfiguration_Password: "rabbitpassword"
     Configuration_Logging_ExceptionLogging_DataBaseConfiguration_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Configuration_Logging_ExceptionLogging_MongoConfiguration_ConnectionString: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_Host: "https://localhost:9200"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_UserName: "elastic"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_Password: "zrZhe7mrQBwVWKnxYQAS"
     Configuration_Logging_ExceptionLogging_ElasticConfiguration_Index: "log-microservice-exception"
     Configuration_RabbitQueues_Host_DefaultHost: "rabbitmq3.default.svc.cluster.local"
     Configuration_RabbitQueues_Host_DefaultUserName: "rabbituser"
     Configuration_RabbitQueues_Host_DefaultPassword: "rabbitpassword"
     Configuration_WebSockets_DataSource: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Socket_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Persistence_Databases_Microservice_AA_DB_ConnectionString: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_AA_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
     Caching_Redis_Server: "svc-redis.default.svc.cluster.local"
  image:
   imagePullPolicy: "Always"
   name: "serkancamur/aa"
   tag: "latest"