apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq-service
  ports:
    - protocol: TCP
      name: http
      port: 15672
      targetPort: 15672