apiVersion: v1
kind: Service
metadata:
  name: production-service
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: {{ .Values.service.ports.external }}
    targetPort: {{ .Values.service.ports.internal }}
    protocol: {{ .Values.service.ports.protocol }}
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}