apiVersion: v1
kind: Service
metadata:
  name: selling-service
spec:
  selector:
    app: selling-pod
  ports:
  - port: 5110
    targetPort: 5139
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.110