apiVersion: v1
kind: Service
metadata:
  name: buying-service
spec:
  selector:
    app: buying-pod
  ports:
  - port: 5105
    targetPort: 26558
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.105