apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv-volume
spec:
  capacity:
    storage: 10Gi
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/opt/mssql"