apiVersion: apps/v1
kind: Deployment
metadata:
  name: agwpublic-deployment
spec:
  selector:
    matchLabels:
      app: agwpublic-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: agwpublic-pod
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: agwpublic-container
          image: serkancamur/agwpublic:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 26920
          env:
            - name: ApplicationName
              value: "Public API Gateway Service"
            - name: Configuration_Authorization_Credential_Email
              value: "Services.Api.Gateway.Public@gateway.service"
            - name: Configuration_Authorization_Credential_Password
              value: "1234"
            - name: Configuration_Localization_TranslationDbConnnectionString
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Localization_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Host
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_Logging_RequestResponseLogging_RabbitConfiguration_UserName
              value: "rabbituser"
            - name: Configuration_Logging_RequestResponseLogging_RabbitConfiguration_Password
              value: "rabbitpassword"
            - name: Configuration_Logging_RequestResponseLogging_DataBaseConfiguration_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_RequestResponseLogging_MongoConfiguration_ConnectionString
              value: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Host
              value: "http://localhost:9200"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_UserName
              value: "elastic"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Password
              value: "mV7BCD4F0E7t1Qa0iVN*"
            - name: Configuration_Logging_RequestResponseLogging_ElasticConfiguration_Index
              value: "log-microservice-request-response"
            - name: Configuration_Logging_ExceptionLogging_RabbitConfiguration_Host
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_Logging_ExceptionLogging_RabbitConfiguration_UserName
              value: "rabbituser"
            - name: Configuration_Logging_ExceptionLogging_RabbitConfiguration_Password
              value: "rabbitpassword"
            - name: Configuration_Logging_ExceptionLogging_DataBaseConfiguration_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_ExceptionLogging_MongoConfiguration_ConnectionString
              value: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_Host
              value: "http://localhost:9200"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_UserName
              value: "elastic"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_Password
              value: "mV7BCD4F0E7t1Qa0iVN*"
            - name: Configuration_Logging_ExceptionLogging_ElasticConfiguration_Index
              value: "log-microservice-exception"
            - name: Configuration_Logging_RuntimeLogging_RabbitConfiguration_Host
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_Logging_RuntimeLogging_RabbitConfiguration_UserName
              value: "rabbituser"
            - name: Configuration_Logging_RuntimeLogging_RabbitConfiguration_Password
              value: "rabbitpassword"
            - name: Configuration_Logging_RuntimeLogging_DataBaseConfiguration_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Logs_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Configuration_Logging_RuntimeLogging_MongoConfiguration_ConnectionString
              value: "mongodb://adminuser:password123@mongo-service.default.svc.cluster.local:27017"
            - name: Configuration_Logging_RuntimeLogging_ElasticConfiguration_Host
              value: "http://localhost:9200"
            - name: Configuration_Logging_RuntimeLogging_ElasticConfiguration_UserName
              value: "elastic"
            - name: Configuration_Logging_RuntimeLogging_ElasticConfiguration_Password
              value: "mV7BCD4F0E7t1Qa0iVN*"
            - name: Configuration_Logging_RuntimeLogging_ElasticConfiguration_Index
              value: "log-microservice-runtime"
            - name: Configuration_RabbitQueues_Host_DefaultHost
              value: "rabbitmq3.default.svc.cluster.local"
            - name: Configuration_RabbitQueues_Host_DefaultUserName
              value: "rabbituser"
            - name: Configuration_RabbitQueues_Host_DefaultPassword
              value: "rabbitpassword"
            - name: Configuration_WebSockets_DataSource
              value: "server=mssql-service.default.svc.cluster.local;DataBase=Microservice_Socket_DB;user=sa;password=Srkn_CMR*1987;MultipleActiveResultSets=true;TrustServerCertificate=Yes"
            - name: Caching_Redis_Server
              value: "svc-redis.default.svc.cluster.local"
          volumeMounts:
            - mountPath: "mnt/data"
              name: volume