apiVersion: v1
kind: Service
metadata:
  name: agwpublic-service
spec:
  selector:
    app: agwpublic-pod
  ports:
  - port: 5099
    targetPort: 20200
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.99