apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  # namespace: redis-cluster
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
   path: /data/redis