apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-deployment
spec:
  selector:
    matchLabels:
      app: logging-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: logging-pod
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: logging-container
          image: serkancamur/logging:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 15455
          volumeMounts:
            - mountPath: "mnt/data"
              name: volume