apiVersion: v1
kind: Service
metadata:
  name: cr-service
spec:
  selector:
    app: cr-pod
  ports:
  - port: 5106
    targetPort: 60403
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.106