FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 31636

ENV ASPNETCORE_URLS=http://+:31636

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["Presentation.UI.Web.Identity/Presentation.UI.Web.Identity.csproj", "Presentation.UI.Web.Identity/"]
RUN dotnet restore "Presentation.UI.Web.Identity/Presentation.UI.Web.Identity.csproj"
COPY . .
WORKDIR "/src/Presentation.UI.Web.Identity"
RUN dotnet build "Presentation.UI.Web.Identity.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Presentation.UI.Web.Identity.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Presentation.UI.Web.Identity.dll"]

#docker build -t serkancamur/presentationuiwebidentity:latest -f Dockerfile_PresentationUIWebIdentity .
#docker push serkancamur/presentationuiwebidentity:latest