FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 26558

ENV ASPNETCORE_URLS=http://+:26558

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["Services.Api.Business.Departments.Buying/Services.Api.Business.Departments.Buying.csproj", "Services.Api.Business.Departments.Buying/"]
RUN dotnet restore "Services.Api.Business.Departments.Buying/Services.Api.Business.Departments.Buying.csproj"
COPY . .
WORKDIR "/src/Services.Api.Business.Departments.Buying"
RUN dotnet build "Services.Api.Business.Departments.Buying.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Api.Business.Departments.Buying.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Api.Business.Departments.Buying.dll"]

#docker build -t serkancamur/buying:latest -f Dockerfile_Buying .