FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 13200

ENV ASPNETCORE_URLS=http://+:13200

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["Services.MQ.AA/Services.MQ.AA.csproj", "Services.MQ.AA/"]
RUN dotnet restore "Services.MQ.AA/Services.MQ.AA.csproj"
COPY . .
WORKDIR "/src/Services.MQ.AA"
RUN dotnet build "Services.MQ.AA.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.AA.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.AA.dll"]

#docker build -t serkancamur/mqaa:latest -f Dockerfile_MQ_AA .