FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 13201

ENV ASPNETCORE_URLS=http://+:13201

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["Services.MQ.Accounting/Services.MQ.Accounting.csproj", "Services.MQ.Accounting/"]
RUN dotnet restore "Services.MQ.Accounting/Services.MQ.Accounting.csproj"
COPY . .
WORKDIR "/src/Services.MQ.Accounting"
RUN dotnet build "Services.MQ.Accounting.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.Accounting.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.Accounting.dll"]

#docker build -t serkancamur/mqaccounting:latest -f Dockerfile_MQ_Accounting .
#docker push serkancamur/mqaccounting:latest