FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 8501

ENV ASPNETCORE_URLS=http://+:8501

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["Presentation.UI.Web/Presentation.UI.Web.csproj", "Presentation.UI.Web/"]
RUN dotnet restore "Presentation.UI.Web/Presentation.UI.Web.csproj"
COPY . .
WORKDIR "/src/Presentation.UI.Web"
RUN dotnet build "Presentation.UI.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Presentation.UI.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Presentation.UI.Web.dll"]

#docker build -t serkancamur/presentationuiweb:latest -f Dockerfile_PresentationUIWeb .