# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  servicesapiauthorization:
    image: servicesapiauthorization
    build:
      context: .
      dockerfile: Services.Api.Authorization/Dockerfile
    ports:
      - 16859:16859
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
