FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 56321

ENV ASPNETCORE_URLS=http://+:56321

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services.MQ.Selling/Services.MQ.Selling.csproj", "Services.MQ.Selling/"]
RUN dotnet restore "Services.MQ.Selling/Services.MQ.Selling.csproj"
COPY . .
WORKDIR "/src/Services.MQ.Selling"
RUN dotnet build "Services.MQ.Selling.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.Selling.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.Selling.dll"]

#docker build -t serkancamur/mqselling:latest -f Dockerfile_MQ_Selling .
#docker push serkancamur/mqselling:latest