FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 4121

ENV ASPNETCORE_URLS=http://+:4121

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Services.MQ.Authorization/Services.MQ.Authorization.csproj", "Services.MQ.Authorization/"]
RUN dotnet restore "Services.MQ.Authorization/Services.MQ.Authorization.csproj"
COPY . .
WORKDIR "/src/Services.MQ.Authorization"
RUN dotnet build "Services.MQ.Authorization.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.Authorization.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.Authorization.dll"]

#docker build -t serkancamur/mqauthorization:latest -f Dockerfile_MQ_Authorization .
#docker push serkancamur/mqauthorization:latest