FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 30206

ENV ASPNETCORE_URLS=http://+:30206

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services.MQ.Storage/Services.MQ.Storage.csproj", "Services.MQ.Storage/"]
RUN dotnet restore "Services.MQ.Storage/Services.MQ.Storage.csproj"
COPY . .
WORKDIR "/src/Services.MQ.Storage"
RUN dotnet build "Services.MQ.Storage.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.Storage.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.Storage.dll"]

#docker build -t serkancamur/mqstorage:latest -f Dockerfile_MQ_Storage .
#docker push serkancamur/mqstorage:latest