FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 60403

ENV ASPNETCORE_URLS=http://+:60403

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Services.Api.Business.Departments.CR/Services.Api.Business.Departments.CR.csproj", "Services.Api.Business.Departments.CR/"]
RUN dotnet restore "Services.Api.Business.Departments.CR/Services.Api.Business.Departments.CR.csproj"
COPY . .
WORKDIR "/src/Services.Api.Business.Departments.CR"
RUN dotnet build "Services.Api.Business.Departments.CR.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Api.Business.Departments.CR.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Api.Business.Departments.CR.dll"]

#docker build -t serkancamur/cr:latest -f Dockerfile_CR .
#docker push serkancamur/cr:latest