FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 49480

ENV ASPNETCORE_URLS=http://+:49480

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["Services.MQ.Production/Services.MQ.Production.csproj", "Services.MQ.Production/"]
RUN dotnet restore "Services.MQ.Production/Services.MQ.Production.csproj"
COPY . .
WORKDIR "/src/Services.MQ.Production"
RUN dotnet build "Services.MQ.Production.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.Production.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.Production.dll"]

#docker build -t serkancamur/mqproduction:latest -f Dockerfile_MQ_Production .
#docker push serkancamur/mqproduction:latest