FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 20200

ENV ASPNETCORE_URLS=http://+:20200

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services.Api.Gateway.Public/Services.Api.Gateway.Public.csproj", "Services.Api.Gateway.Public/"]
RUN dotnet restore "Services.Api.Gateway.Public/Services.Api.Gateway.Public.csproj"
COPY . .
WORKDIR "/src/Services.Api.Gateway.Public"
RUN dotnet build "Services.Api.Gateway.Public.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Api.Gateway.Public.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Api.Gateway.Public.dll"]

#docker build -t serkancamur/agwpublic:latest -f Dockerfile_AGW_Public .
#docker push serkancamur/agwpublic:latest