FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 58984

ENV ASPNETCORE_URLS=http://+:58984

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Services.Api.Business.Departments.Storage/Services.Api.Business.Departments.Storage.csproj", "Services.Api.Business.Departments.Storage/"]
RUN dotnet restore "Services.Api.Business.Departments.Storage/Services.Api.Business.Departments.Storage.csproj"
COPY . .
WORKDIR "/src/Services.Api.Business.Departments.Storage"
RUN dotnet build "Services.Api.Business.Departments.Storage.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Api.Business.Departments.Storage.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Api.Business.Departments.Storage.dll"]

#docker build -t serkancamur/storage:latest -f Dockerfile_Storage .
#docker push serkancamur/storage:latest