FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5239

ENV ASPNETCORE_URLS=http://+:5239

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Services.Scheduling.Diagnostics.HealthCheck/Services.Scheduling.Diagnostics.HealthCheck.csproj", "Services.Scheduling.Diagnostics.HealthCheck/"]
RUN dotnet restore "Services.Scheduling.Diagnostics.HealthCheck/Services.Scheduling.Diagnostics.HealthCheck.csproj"
COPY . .
WORKDIR "/src/Services.Scheduling.Diagnostics.HealthCheck"
RUN dotnet build "Services.Scheduling.Diagnostics.HealthCheck.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Scheduling.Diagnostics.HealthCheck.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Scheduling.Diagnostics.HealthCheck.dll"]

#docker build -t serkancamur/healthcheck:latest -f Dockerfile_HealthCheck .
#docker push serkancamur/healthcheck:latest