FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 59402

ENV ASPNETCORE_URLS=http://+:59402

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Services.MQ.Finance/Services.MQ.Finance.csproj", "Services.MQ.Finance/"]
RUN dotnet restore "Services.MQ.Finance/Services.MQ.Finance.csproj"
COPY . .
WORKDIR "/src/Services.MQ.Finance"
RUN dotnet build "Services.MQ.Finance.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.MQ.Finance.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.MQ.Finance.dll"]

#docker build -t serkancamur/mqfinance:latest -f Dockerfile_MQ_Finance .
#docker push serkancamur/mqfinance:latest