FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 32355

ENV ASPNETCORE_URLS=http://+:32355

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services.Api.Business.Departments.Finance/Services.Api.Business.Departments.Finance.csproj", "Services.Api.Business.Departments.Finance/"]
RUN dotnet restore "Services.Api.Business.Departments.Finance/Services.Api.Business.Departments.Finance.csproj"
COPY . .
WORKDIR "/src/Services.Api.Business.Departments.Finance"
RUN dotnet build "Services.Api.Business.Departments.Finance.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Api.Business.Departments.Finance.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Api.Business.Departments.Finance.dll"]

#docker build -t serkancamur/finance:latest -f Dockerfile_Finance .
#docker push serkancamur/finance:latest