FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 34308

ENV ASPNETCORE_URLS=http://+:34308

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services.Api.Business.Departments.AA/Services.Api.Business.Departments.AA.csproj", "Services.Api.Business.Departments.AA/"]
RUN dotnet restore "Services.Api.Business.Departments.AA/Services.Api.Business.Departments.AA.csproj"
COPY . .
WORKDIR "/src/Services.Api.Business.Departments.AA"
RUN dotnet build "Services.Api.Business.Departments.AA.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Services.Api.Business.Departments.AA.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Services.Api.Business.Departments.AA.dll"]

#docker build -t serkancamur/aa:latest -f Dockerfile_AA .
#docker push serkancamur/aa:latest