apiVersion: v1
kind: Service
metadata:
  name: it-service
spec:
  selector:
    app: it-pod
  ports:
  - port: 5108
    targetPort: 65390
    protocol: TCP
  type: LoadBalancer
  clusterIP: 10.102.2.108